
spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://192.168.0.32:5432/postgres
    username: postgres
    password:

server:
  port: 8090
