spring:
  batch:
    initialize-schema: never
  datasource:
    url: jdbc:postgresql://192.168.0.32:5432/postgres
    username: postgres
    password:
  kafka:
    consumer:
      bootstrap-servers: 192.168.0.32:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: batch-worker
      properties: {'spring.json.trusted.packages': '*'}
