version: '2'
services:
  heracles-postgresql:
    image: postgres:9.6.15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - 5432:5432

volumes:
  pgdata: