spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:postgresql://192.168.0.32:5432/postgres
    username: postgres
    password:
  kafka:
    producer:
      bootstrap-servers: 192.168.0.32:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8090
